pipeline {
    agent any
    tools {
        maven 'Maven' //引号里的Maven不要改
    }
    stages {
        stage('Test') {
            steps {
                withSonarQubeEnv('SonarQube') { //引号里的SonarQube不要改
                    sh 'mvn -f MachineLearning/pom.xml clean sonar:sonar'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -f MachineLearning/pom.xml package'
                archive 'target/MachineLearning.war' //制品路径需要修改
            }
        }
        stage('Deploy') {
            steps { //所有的group1_demo需要修改
                sh 'docker stop ExcellentEngineers  || true'
                sh 'docker rm ExcellentEngineers  || true'
                sh 'docker run --name ExcellentEngineers  -p 23333:8080 -d dordoka/tomcat' //端口11111需要修改
                sh 'docker cp target/MachineLearning.war ExcellentEngineers:/opt/tomcat/webapps/' //制品路径需要修改
            }
        }
    }
}
